### ISSUE TITLE
base64 error with ruby1.9

### ISSUE THREAD

**Issue by benoitc** [jchris/couchrest#3]
on Ubuntu 9.04 jaunty with ruby 1.9.0 (2008-06-20 revision 17482)  I get the error : 
/var/lib/gems/1.9.0/gems/couchrest-0.33/lib/couchrest/core/database.rb:2:in `require': no such file to load -- base64 (LoadError)
    from /var/lib/gems/1.9.0/gems/couchrest-0.33/lib/couchrest/core/database.rb:2:in`<top (required)>'
    from /var/lib/gems/1.9.0/gems/couchrest-0.33/lib/couchrest/core/server.rb:53:in `database'
    from /var/lib/gems/1.9.0/gems/couchrest-0.33/lib/couchrest/core/server.rb:59:in`database!'
    from /var/lib/gems/1.9.0/gems/couchrest-0.33/lib/couchrest.rb:138:in `database!'
    from /usr/local/aimpl-version/aimpl/scripts/make_pl.rb:6:in`<main>'

**Comment by deepj** [comment]
Update to newer version of Ruby 1.9.1

**Comment by benoitc** [comment]
yes this is definitly what I had to do though most of current distribution don't have ruby 1.9.1

**Comment by jo** [comment]
You should use Array.pack and string.unpack "m"

Greetings,
Johannes

**Comment by benoitc** [comment]
i installed ruby 1.9.1 (easier way in time limited). But anyway I'm not sure couchrest should require 1.9.1 actually. very little linux distribution have it in stable.

**Comment by jo** [comment]
I meant couchrest could use Array.pack("m*") instead of using Base64.encode64 to obviate that version dependency.

http://www.ruby-forum.com/topic/132076

Greetings
Johannes
